.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. xogecoin_qt test_xogecoin_qt
clean: FORCE
	$(MAKE) -C .. xogecoin_qt_clean test_xogecoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_xogecoin_qt_check
xogecoin-qt xogecoin-qt.exe: FORCE
	 $(MAKE) -C .. xogecoin_qt
apk: FORCE
	$(MAKE) -C .. xogecoin_qt_apk
